Added --stdin-data argument
sharkdp/hyperfine pull request #563
Opened 2022-09-11 22:07 UTC by snease

This argument accepts a path to a file. The data contained in the file will be passed to the command via stdin.

Closes sharkdp/hyperfine#541

2022-10-13 20:18 UTC, sharkdp commented on src/options.rs
> +    pub command_input_policy: CommandInputPolicy,
Maybe move this above `command_output_policy`?

2022-10-13 20:20 UTC, sharkdp commented on src/benchmark/executor.rs
>  use std::process::{ExitStatus, Stdio};
Can we please fie warning here (unused import: `Stdio`)

2022-10-13 20:21 UTC, sharkdp commented on src/benchmark/executor.rs
> +    let stdin = command_input_policy.get_stdin()?;
move this above the `stdout, sterr` line to be consistent with the ordering elsewhere (input before output)?

2022-10-13 20:21 UTC, sharkdp commented on src/cli.rs
> +            Arg::new("stdin-data")
Can we maybe rename this to `--input`, in analogy to `--output`? Or is there any reason against this?

2022-10-13 20:23 UTC, sharkdp commented on src/cli.rs
> +            Arg::new("stdin-data")
And also change the option such that it works similar to `--output`. Maybe:
```
--input <FROM>
  Control where the input of the benchmark comes from. <FROM> can be:

  null: Read from /dev/null (the default).

  <FILE>: Read the input from the given file
```

2022-10-13 20:24 UTC, sharkdp commented on src/options.rs
> +    /// Redirect input from a file
```suggestion
    /// Read input from a file
```

2022-10-13 20:24 UTC, sharkdp commented on src/options.rs
> +    /// Redirect from the null device
```suggestion
    /// Read from the null device
```

2022-10-13 20:24 UTC, sharkdp requested changes
Thank you very much for your contribution!

2022-10-15 19:37 UTC, snease commented
Happy to help! Thanks for creating a great project.

2022-10-29 13:07 UTC, sharkdp commented on tests/example_stdin_data
> +This data is passed to the command via stdin
Minor: "stdin" is usually input from the terminal. While this is input from a file. This is a bit confusing when reading the test below. Can we maybe change this to
```suggestion
This text is part of a file
```

2022-10-29 13:08 UTC, sharkdp commented on tests/integration_tests.rs
> +}
```suggestion
fn can_pass_input_to_command_from_a_file() {
    hyperfine()
        .arg("--runs=1")
        .arg("--input=example_input_file.txt")
        .arg("--show-output")
        .arg("cat")
        .assert()
        .success()
        .stdout(predicate::str::contains(
            "This text is part of a file",
        ));
}
```

2022-10-29 13:09 UTC, sharkdp commented on tests/integration_tests.rs
> +        .arg("--input=example_stdin_data_invalid")
```suggestion
        .arg("--input=example_non_existent_file.txt")
```

2022-10-29 13:09 UTC, sharkdp commented on src/benchmark/executor.rs
> +    let stdin = command_input_policy.get_stdin()?;
That has not been resolved yet.

2023-03-15 08:25 UTC, sharkdp approved these changes

2023-03-15 08:33 UTC, merged